# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Brewery.destroy_all
Beer.destroy_all 
Bar.destroy_all
BeerExperience.destroy_all

Brewery.create(name: 'Haymarket Brewery', city: 'Chicago', state: 'IL', country: 'USA', website: 'http://haymarketbrewing.com/')
Brewery.create(name: 'Ska Brewing Company', city: 'Durango', state: 'CO', country: 'USA', website: 'http://www.skabrewing.com/')
Brewery.create(name: 'Greenbush Brewing Company', city: 'Sawyer', state: 'MI', country: 'USA', website: 'http://www.greenbushbrewing.com/')
Brewery.create(name: 'Against the Grain Brewery', city: 'Louisville', state: 'KY', country: 'USA', website: 'http://www.atgbrewery.com/')
Brewery.create(name: 'Victory Brewing Company', city: 'Downingtown', state: 'PA', country: 'USA', website: 'http://victorybeer.com/')
Brewery.create(name: 'Southern Tier Brewing Company', city: 'Lakewood', state: 'NY', country: 'USA', website: 'http://www.stbcbeer.com/stbc/')
Brewery.create(name: 'Revolution Brewing', city: 'Chicago', state: 'IL', country: 'USA', website: 'http://revbrew.com/')
Brewery.create(name: 'Goose Island Brewery', city: 'Chicago', state: 'IL', country: 'USA', website: 'http://www.gooseisland.com/')
Brewery.create(name: 'Two Brothers', city: 'Warrenville', state: 'IL', country: 'USA', website: 'http://www.twobrosbrew.com/')

Beer.create(name: 'Speakerswagon Pilsner', brewery_id: 1, style: 'Pilsner', abv: 5.8, clean: 1, crisp: 1, hoppy: 1)
Beer.create(name: 'Oscar\'s Pardon Dry-Hopped Belgian Pale Ale', brewery_id: 1, style: 'Pale Ale', abv: 4.5, belgian: 1)
Beer.create(name: 'Mother Jones Dry-Hopped Abbey Style Dubbel', brewery_id: 1, style: 'Abbey Dubbel', abv: 7.5, chocolate: 1, fruity: 1, belgian: 1)
Beer.create(name: 'Mathias Imperial IPA', brewery_id: 1, style: 'IPA', abv: 10, citrus: 1)
Beer.create(name: 'Bieber\'s Banana Hammock Hefeweizen', brewery_id: 1, style: 'Hefeweizen', abv: 5, banana: 1, cloves: 1, wheat: 1)
Beer.create(name: 'Hogbutcher Belgian IPA', brewery_id: 1, style: 'IPA', abv: 7.5, belgian: 1)
Beer.create(name: 'Rive Gauche Biere de Garde', brewery_id: 1, style: 'Farmhouse', abv: 5.5, clean: 1, sweet: 1, citrus: 1)
Beer.create(name: 'Tiepolo Blonde', brewery_id: 1, style: 'Blonde', abv: 4.5, crisp: 1, fruity: 1)
Beer.create(name: 'Rubber Monkey', brewery_id: 1, style: 'IPA', abv: 7, citrus: 1, wheat: 1, belgian: 1)
Beer.create(name: 'Ska Modus Hoperandi', brewery_id: 2, style: 'IPA', abv: 6.8, srm: 7, hoppy: 1, smooth: 1, bitter: 1, sweet: 1, caramel: 1, citrus: 1, fruity: 1, grapefruit: 1, pine: 1)
Beer.create(name: 'Dunegras', brewery_id: 3, style: 'IPA', abv: 6.7, ibu: 67)
Beer.create(name: 'Local Option Morning Wood', brewery_id: 4, style: 'Hybrid Ale', abv: 7, coffee: 1)
Beer.create(name: 'Golden Monkey', brewery_id: 5, style: 'Golden Ale', abv: 9.5, rich: 1, fruity: 1, belgian: 1)
Beer.create(name: 'Gemini', brewery_id: 6, style: 'Imperial Blended Ale', abv: 9, rich: 1, fruity: 1, belgian: 1)
Beer.create(name: '2X IPA', brewery_id: 6, style: 'IPA', abv: 8.2, bitter: 1, sweet: 1, citrus: 1, floral: 1, fruity: 1, grapefruit: 1, lemon: 1, pine: 1)
Beer.create(name: 'Sock Chicken', brewery_id: 1, style: 'IPA', abv: 7, rich: 1, fruity: 1, belgian: 1)
Beer.create(name: 'Hard Times American IPA', brewery_id: 1, style: 'IPA', abv: 6)
Beer.create(name: 'Iron Fist', brewery_id: 7, style: 'Pale Ale')
Beer.create(name: 'Eugene Porter', brewery_id: 7, style: 'Porter', abv: 6.8, ibu: 28, caramel: 1, chocolate: 1, belgian: 1)
Beer.create(name: 'Bottom Up Wit', brewery_id: 7, style: 'Witbier', abv: 5, ibu: 14, crisp: 1, citrus: 1, wheat: 1, belgian: 1)
Beer.create(name: 'Black Power', brewery_id: 7, style: 'Oatmeal Stout', smooth: 1, chocolate: 1)
Beer.create(name: 'Anti-Hero IPA', brewery_id: 7, style: 'IPA', abv: 6.5, ibu: 70, crisp: 1, bitter: 1, citrus: 1, floral: 1)
Beer.create(name: 'Cross of Gold', brewery_id: 7, style: 'Golden Ale', crisp: 1)
Beer.create(name: 'Coup d\'Etat', brewery_id: 7, style: 'Saison', abv: 7.6, ibu: 50, earthy: 1, citrus: 1)
Beer.create(name: 'Cuddy Blueberry', brewery_id: 8, style: 'Blueberry Ale', abv: 5)
Beer.create(name: 'Wrigleyville White', brewery_id: 8, style: 'Witbier', abv: 5)
Beer.create(name: 'Blonde', brewery_id: 8, style: 'Blonde', abv: 5, spicy: 1, citrus: 1, belgian: 1)
Beer.create(name: 'Sunny', brewery_id: 8, style: 'Kolsch', abv: 5)
Beer.create(name: 'Summertime', brewery_id: 8, style: 'Kolsch', abv: 4.7, lemon: 1)
Beer.create(name: '312', brewery_id: 8, style: 'Wheat Ale', abv: 4.2, creamy: 1, fruity: 1)
Beer.create(name: 'Green Line', brewery_id: 8, style: 'Pale Ale', abv: 5, crisp: 1, citrus: 1)
Beer.create(name: 'Honker\'s', brewery_id: 8, style: 'ESB', abv: 4.3, fruity: 1)
Beer.create(name: 'Star Cluster IPA', brewery_id: 8, style: 'IPA', abv: 6.5, hoppy: 1)
Beer.create(name: 'India Pale Ale', brewery_id: 8, style: 'IPA', abv: 5.9, hoppy: 1, fruity: 1, grapefruit: 1)
Beer.create(name: 'Foxxy Brown Ale', brewery_id: 8, style: 'Brown Ale', abv: 6.3, malty: 1, chocolate: 1)
Beer.create(name: 'Nut Brown Ale', brewery_id: 8, style: 'Brown Ale', abv: 5.3, malty: 1, chocolate: 1, nutty: 1)
Beer.create(name: 'Sofie', brewery_id: 8, style: 'Farmhouse', abv: 6.5, citrus: 1, vanilla: 1, belgian: 1)
Beer.create(name: 'Pepe Nero', brewery_id: 8, style: 'Farmhouse', abv: 6, creamy: 1, belgian: 1)
Beer.create(name: 'Matilda', brewery_id: 8, style: 'Pale Ale', abv: 7, fruity: 1, belgian: 1)
Beer.create(name: 'Pere Jacques', brewery_id: 8, style: 'Abbey', abv: 8, rich: 1, caramel: 1, fruity: 1, belgian: 1)
Beer.create(name: 'Fleur', brewery_id: 8, style: 'Pale Ale', abv: 7, crisp: 1, sweet: 1, tart: 1, belgian: 1)
Beer.create(name: 'Marisol', brewery_id: 8, style: 'Golden Ale', abv: 6.1, creamy: 1, spicy: 1, citrus: 1, fruity: 1, belgian: 1)
Beer.create(name: 'Juliet', brewery_id: 8, style: 'Sour Ale', abv: 6.3, sour: 1, fruity: 1)
Beer.create(name: 'Lolita', brewery_id: 8, style: 'Wild Ale', abv: 7, sour: 1)
Beer.create(name: 'Queen-OA', brewery_id: 8, style: 'Gluten-Free', abv: 6.2, citrus: 1, fruity: 1, grapefruit: 1)
Beer.create(name: 'Ebel\'s Weiss', brewery_id: 9, style: 'Hefeweizen', abv: 4.7, spicy: 1, sweet: 1, banana: 1, cloves: 1, vanilla: 1)

Bar.create(name: 'Haymarket Brewery', address: '737 W Randolph', city: 'Chicago', state: 'IL', zip: 60661, phone: '3126380700', website: 'http://haymarketbrewing.com/')
Bar.create(name: 'Revolution Brewing', address: '2323 N Milwaukee Ave', city: 'Chicago', state: 'IL', zip: 60647, phone: '7732272739', website: 'http://revbrew.com/')
Bar.create(name: 'Goose Island Brewery', address: '3535 N Clark St', city: 'Chicago', state: 'IL', zip: 60657, phone: '7738329040', website: 'http://www.gooseisland.com/')

BeerExperience.create(beer_id: 1, bar_id: 1, home: 1, local: 1, draft: 1, rarity: 5)
BeerExperience.create(beer_id: 2, bar_id: 1, home: 1, local: 1, draft: 1, rarity: 5)
BeerExperience.create(beer_id: 3, bar_id: 1, home: 1, local: 1, draft: 1, rarity: 5)
BeerExperience.create(beer_id: 4, bar_id: 1, home: 1, local: 1, draft: 1, rarity: 5)
BeerExperience.create(beer_id: 5, bar_id: 1, home: 1, local: 1, draft: 1, rarity: 5)
BeerExperience.create(beer_id: 6, bar_id: 1, home: 1, local: 1, draft: 1, rarity: 5)
BeerExperience.create(beer_id: 7, bar_id: 1, home: 1, local: 1, draft: 1, rarity: 5)
BeerExperience.create(beer_id: 8, bar_id: 1, home: 1, local: 1, draft: 1, rarity: 5)
BeerExperience.create(beer_id: 9, bar_id: 1, draft: 1, rarity: 4)
BeerExperience.create(beer_id: 10, bar_id: 1, draft: 1, rarity: 4)
BeerExperience.create(beer_id: 11, bar_id: 1, draft: 1, rarity: 4)
BeerExperience.create(beer_id: 12, bar_id: 1, draft: 1, rarity: 4)
BeerExperience.create(beer_id: 13, bar_id: 1, draft: 1, rarity: 3)
BeerExperience.create(beer_id: 14, bar_id: 1, draft: 1, rarity: 4)
BeerExperience.create(beer_id: 15, bar_id: 1, draft: 1, rarity: 3)
BeerExperience.create(beer_id: 16, bar_id: 1, draft: 1, rarity: 5)
BeerExperience.create(beer_id: 17, bar_id: 1, draft: 1, rarity: 4)
BeerExperience.create(beer_id: 18, bar_id: 2, rarity: 5)
BeerExperience.create(beer_id: 19, bar_id: 2, rarity: 5)
BeerExperience.create(beer_id: 20, bar_id: 2, rarity: 5)
BeerExperience.create(beer_id: 21, bar_id: 2, rarity: 5)
BeerExperience.create(beer_id: 22, bar_id: 2, rarity: 4)
BeerExperience.create(beer_id: 23, bar_id: 2, rarity: 5)
BeerExperience.create(beer_id: 24, bar_id: 2, rarity: 4)
BeerExperience.create(beer_id: 25, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 5)
BeerExperience.create(beer_id: 26, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 5)
BeerExperience.create(beer_id: 27, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 5)
BeerExperience.create(beer_id: 28, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 5)
BeerExperience.create(beer_id: 29, bar_id: 3, home: 1, local: 1, rarity: 2)
BeerExperience.create(beer_id: 30, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 1)
BeerExperience.create(beer_id: 31, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 4)
BeerExperience.create(beer_id: 32, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 1)
BeerExperience.create(beer_id: 33, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 5)
BeerExperience.create(beer_id: 34, bar_id: 3, home: 1, local: 1, rarity: 5)
BeerExperience.create(beer_id: 35, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 5)
BeerExperience.create(beer_id: 36, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 5)
BeerExperience.create(beer_id: 37, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 3)
BeerExperience.create(beer_id: 38, bar_id: 3, home: 1, local: 1, rarity: 3)
BeerExperience.create(beer_id: 39, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 3)
BeerExperience.create(beer_id: 40, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 3)
BeerExperience.create(beer_id: 41, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 4)
BeerExperience.create(beer_id: 42, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 4)
BeerExperience.create(beer_id: 43, bar_id: 3, home: 1, local: 1, rarity: 4)
BeerExperience.create(beer_id: 44, bar_id: 3, home: 1, local: 1, rarity: 4)
BeerExperience.create(beer_id: 45, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 5)
BeerExperience.create(beer_id: 46, bar_id: 3, local: 1, draft: 1, rarity: 3)

Team.create(name: 'Emily Ellison', description: 'Data Nerd.', image: 'emily_in_color.jpg')
Team.create(name: 'Stella Fayman', description: 'Entrepreneurial Rockstar.', image: 'stella_in_color.jpg')
Team.create(name: 'Zak Boswell', description: 'UX Ninja.', image: 'zak_in_color.jpg')
Team.create(name: 'Fernando Diaz', description: 'Code Detective.', image: 'fernando_in_color.jpg')
Team.create(name: 'Mike Ebert', description: 'Agile Scrum Master.', image: 'mike_in_color.png')
Team.create(name: 'Chad Hendry', description: 'Programming Guru.', image: 'chad.jpg')