# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Brewery.destroy_all
# Beer.destroy_all 
# Bar.destroy_all
# BeerExperience.destroy_all
# 
# Brewery.create(name: 'Haymarket', city: 'Chicago', state: 'IL', country: 'USA', website: 'http://haymarketbrewing.com/')
# Brewery.create(name: 'Ska', city: 'Durango', state: 'CO', country: 'USA', website: 'http://www.skabrewing.com/')
# Brewery.create(name: 'Greenbush', city: 'Sawyer', state: 'MI', country: 'USA', website: 'http://www.greenbushbrewing.com/')
# Brewery.create(name: 'Against the Grain', city: 'Louisville', state: 'KY', country: 'USA', website: 'http://www.atgbrewery.com/')
# Brewery.create(name: 'Victory', city: 'Downingtown', state: 'PA', country: 'USA', website: 'http://victorybeer.com/')
# Brewery.create(name: 'Southern Tier', city: 'Lakewood', state: 'NY', country: 'USA', website: 'http://www.stbcbeer.com/stbc/')
# Brewery.create(name: 'Revolution', city: 'Chicago', state: 'IL', country: 'USA', website: 'http://revbrew.com/')
# Brewery.create(name: 'Goose Island', city: 'Chicago', state: 'IL', country: 'USA', website: 'http://www.gooseisland.com/')
# Brewery.create(name: 'Two Brothers', city: 'Warrenville', state: 'IL', country: 'USA', website: 'http://www.twobrosbrew.com/')
# Brewery.create(name: 'Allagash', city: 'Portland', state: 'ME', country: 'USA')
# Brewery.create(name: 'Heineken', country: 'Netherlands')
# Brewery.create(name: 'Bells', city: 'Kalamazoo', state: 'MI', country: 'USA')
# Brewery.create(name: 'Blue Moon', city: 'Golden', state: 'CO', country: 'USA')
# Brewery.create(name: 'Brasserie Dupont', country: 'Belgium')
# Brewery.create(name: 'Brooklyn', city: 'Brooklyn', state: 'NY', country: 'USA')
# Brewery.create(name: 'Molson Coors', city: 'Golden', state: 'CO', country: 'USA')
# Brewery.create(name: 'Group Modelo', country: 'Mexico')
# Brewery.create(name: 'Dark Horse', city: 'Marshall', state: 'MI', country: 'USA')
# Brewery.create(name: 'Dogfish Head', city: 'Wilmington', state: 'DE', country: 'USA')
# Brewery.create(name: 'Cuauhtemoc-Moctezuma Brewery', country: 'Mexico')
# Brewery.create(name: 'Duchesse De Bourgogne', country: 'Belgium')
# Brewery.create(name: 'Firestone Walker', city: 'Paso Robles', state: 'CA', country: 'USA')
# Brewery.create(name: 'Gulden', country: 'Belgium')
# Brewery.create(name: 'Half Acre', city: 'Chicago', state: 'IL', country: 'USA')
# Brewery.create(name: 'Heineken Netherlands', country: 'Netherlands')
# Brewery.create(name: 'Hitachino Nest', country: 'Japan')
# Brewery.create(name: 'Left Hand', city: 'Longmont', state: 'CO', country: 'USA')
# Brewery.create(name: 'Metropolitan', city: 'Chicago', state: 'IL', country: 'USA')
# Brewery.create(name: 'SAB Miller', city: 'Milwaukee', state: 'WI', country: 'USA')
# Brewery.create(name: 'North Coast', city: 'Fort Bragg', state: 'CA', country: 'USA')
# Brewery.create(name: 'Ommegang', city: 'Cooperstown', state: 'NY', country: 'USA')
# Brewery.create(name: 'Revolution', city: 'Chicago', state: 'IL', country: 'USA')
# Brewery.create(name: 'Sixpoint', city: 'Brooklyn', state: 'NY', country: 'USA')
# Brewery.create(name: 'Ska Modus', city: 'Durango', state: 'CO', country: 'USA')
# Brewery.create(name: 'St. Feuillien', country: 'Belgium')
# Brewery.create(name: 'AB InBev', country: 'Belgium')
# Brewery.create(name: 'Stone', city: 'Escondido', state: 'CA', country: 'USA')
# Brewery.create(name: 'Three Floyds', city: 'Munster', state: 'IN', country: 'USA')
# Brewery.create(name: 'Timmermans', country: 'Belgium')
# Brewery.create(name: 'Brouwerij Bosteels', country: 'Belgium')
# Brewery.create(name: 'Two Brothers', city: 'Warrenville', state: 'IL', country: 'USA')
# Brewery.create(name: 'Tyranena Rocky\'s', city: 'Lake Mills', state: 'WI', country: 'USA')
# Brewery.create(name: 'Unibroue', city: 'Chambly', state: 'QC', country: 'Canada')
# Brewery.create(name: 'Virtue', city: 'Chicago', state: 'IL', country: 'USA')
# Brewery.create(name: 'Well\'s', country: 'England')
# 
# Beer.create(name: 'Speakerswagon Pilsner', brewery_id: 1, style: 'Pilsner', abv: 5.8, clean: 1, crisp: 1, hoppy: 1)
# Beer.create(name: 'Oscar\'s Pardon Dry-Hopped Belgian Pale Ale', brewery_id: 1, style: 'Pale Ale', abv: 4.5, belgian: 1)
# Beer.create(name: 'Mother Jones Dry-Hopped Abbey Style Dubbel', brewery_id: 1, style: 'Abbey Dubbel', abv: 7.5, chocolate: 1, fruity: 1, belgian: 1)
# Beer.create(name: 'Mathias Imperial IPA', brewery_id: 1, style: 'IPA', abv: 10, citrus: 1)
# Beer.create(name: 'Bieber\'s Banana Hammock Hefeweizen', brewery_id: 1, style: 'Hefeweizen', abv: 5, banana: 1, cloves: 1, wheat: 1)
# Beer.create(name: 'Hogbutcher Belgian IPA', brewery_id: 1, style: 'IPA', abv: 7.5, belgian: 1)
# Beer.create(name: 'Rive Gauche Biere de Garde', brewery_id: 1, style: 'Farmhouse', abv: 5.5, clean: 1, sweet: 1, citrus: 1)
# Beer.create(name: 'Tiepolo Blonde', brewery_id: 1, style: 'Blonde', abv: 4.5, crisp: 1, fruity: 1)
# Beer.create(name: 'Rubber Monkey', brewery_id: 1, style: 'IPA', abv: 7, citrus: 1, wheat: 1, belgian: 1)
# Beer.create(name: 'Modus Hoperandi', brewery_id: 2, style: 'IPA', abv: 6.8, srm: 7, hoppy: 1, smooth: 1, bitter: 1, sweet: 1, caramel: 1, citrus: 1, fruity: 1, grapefruit: 1, pine: 1)
# Beer.create(name: 'Dunegras', brewery_id: 3, style: 'IPA', abv: 6.7, ibu: 67)
# Beer.create(name: 'Local Option Morning Wood', brewery_id: 4, style: 'Hybrid Ale', abv: 7, coffee: 1)
# Beer.create(name: 'Golden Monkey', brewery_id: 5, style: 'Golden Ale', abv: 9.5, rich: 1, fruity: 1, belgian: 1)
# Beer.create(name: 'Gemini', brewery_id: 6, style: 'Imperial Blended Ale', abv: 9, rich: 1, fruity: 1, belgian: 1)
# Beer.create(name: '2X IPA', brewery_id: 6, style: 'IPA', abv: 8.2, bitter: 1, sweet: 1, citrus: 1, floral: 1, fruity: 1, grapefruit: 1, lemon: 1, pine: 1)
# Beer.create(name: 'Sock Chicken', brewery_id: 1, style: 'IPA', abv: 7, rich: 1, fruity: 1, belgian: 1)
# Beer.create(name: 'Hard Times American IPA', brewery_id: 1, style: 'IPA', abv: 6)
# Beer.create(name: 'Iron Fist', brewery_id: 7, style: 'Pale Ale')
# Beer.create(name: 'Eugene Porter', brewery_id: 7, style: 'Porter', abv: 6.8, ibu: 28, caramel: 1, chocolate: 1, belgian: 1)
# Beer.create(name: 'Bottom Up Wit', brewery_id: 7, style: 'Witbier', abv: 5, ibu: 14, crisp: 1, citrus: 1, wheat: 1, belgian: 1)
# Beer.create(name: 'Black Power', brewery_id: 7, style: 'Oatmeal Stout', smooth: 1, chocolate: 1)
# Beer.create(name: 'Anti-Hero IPA', brewery_id: 7, style: 'IPA', abv: 6.5, ibu: 70, crisp: 1, bitter: 1, citrus: 1, floral: 1)
# Beer.create(name: 'Cross of Gold', brewery_id: 7, style: 'Golden Ale', crisp: 1)
# Beer.create(name: 'Coup d\'Etat', brewery_id: 7, style: 'Saison', abv: 7.6, ibu: 50, earthy: 1, citrus: 1)
# Beer.create(name: 'Cuddy Blueberry', brewery_id: 8, style: 'Blueberry Ale', abv: 5)
# Beer.create(name: 'Wrigleyville White', brewery_id: 8, style: 'Witbier', abv: 5)
# Beer.create(name: 'Blonde', brewery_id: 8, style: 'Blonde', abv: 5, spicy: 1, citrus: 1, belgian: 1)
# Beer.create(name: 'Sunny', brewery_id: 8, style: 'Kolsch', abv: 5)
# Beer.create(name: 'Summertime', brewery_id: 8, style: 'Kolsch', abv: 4.7, lemon: 1)
# Beer.create(name: '312', brewery_id: 8, style: 'Wheat Ale', abv: 4.2, creamy: 1, sweet: 1, citrus: 1, fruity: 1)
# Beer.create(name: 'Green Line', brewery_id: 8, style: 'Pale Ale', abv: 5, crisp: 1, citrus: 1)
# Beer.create(name: 'Honker\'s', brewery_id: 8, style: 'ESB', abv: 4.3, fruity: 1)
# Beer.create(name: 'Star Cluster IPA', brewery_id: 8, style: 'IPA', abv: 6.5, hoppy: 1)
# Beer.create(name: 'India Pale Ale', brewery_id: 8, style: 'IPA', abv: 5.9, hoppy: 1, fruity: 1, grapefruit: 1)
# Beer.create(name: 'Foxxy Brown Ale', brewery_id: 8, style: 'Brown Ale', abv: 6.3, malty: 1, chocolate: 1)
# Beer.create(name: 'Nut Brown Ale', brewery_id: 8, style: 'Brown Ale', abv: 5.3, malty: 1, chocolate: 1, nutty: 1)
# Beer.create(name: 'Sofie', brewery_id: 8, style: 'Farmhouse', abv: 6.5, citrus: 1, vanilla: 1, belgian: 1)
# Beer.create(name: 'Pepe Nero', brewery_id: 8, style: 'Farmhouse', abv: 6, creamy: 1, belgian: 1)
# Beer.create(name: 'Matilda', brewery_id: 8, style: 'Pale Ale', abv: 7, fruity: 1, belgian: 1)
# Beer.create(name: 'Pere Jacques', brewery_id: 8, style: 'Abbey', abv: 8, rich: 1, caramel: 1, fruity: 1, belgian: 1)
# Beer.create(name: 'Fleur', brewery_id: 8, style: 'Pale Ale', abv: 7, crisp: 1, sweet: 1, tart: 1, belgian: 1)
# Beer.create(name: 'Marisol', brewery_id: 8, style: 'Golden Ale', abv: 6.1, creamy: 1, spicy: 1, citrus: 1, fruity: 1, belgian: 1)
# Beer.create(name: 'Juliet', brewery_id: 8, style: 'Sour Ale', abv: 6.3, sour: 1, fruity: 1)
# Beer.create(name: 'Lolita', brewery_id: 8, style: 'Wild Ale', abv: 7, sour: 1)
# Beer.create(name: 'Queen-OA', brewery_id: 8, style: 'Gluten-Free', abv: 6.2, citrus: 1, fruity: 1, grapefruit: 1)
# Beer.create(name: 'Ebel\'s Weiss', brewery_id: 9, style: 'Hefeweizen', abv: 4.7, spicy: 1, sweet: 1, banana: 1, cloves: 1, vanilla: 1)
# Beer.create(name: 'Black Stout', brewery_id: 10, style: 'Stout', abv: 7.5, sweet: 1, belgian: 1)
# Beer.create(name: 'White Ale', brewery_id: 10, style: 'Ale', abv: 5.2, sweet: 1, citrus: 1, fruity: 1, wheat: 1, belgian: 1)
# Beer.create(name: 'Amstel Light', brewery_id: 11, style: 'Lager', abv: 3.5, clean: 1, crisp: 1)
# Beer.create(name: 'Oberon', brewery_id: 12, style: 'Wheat Ale', abv: 5.8, spicy: 1, sweet: 1, fruity: 1, wheat: 1)
# Beer.create(name: 'Belgian White Ale', brewery_id: 13, style: 'Ale', abv: 5.4, sweet: 1, citrus: 1, fruity: 1, wheat: 1, belgian: 1)
# Beer.create(name: 'Saison Dupont', brewery_id: 14, style: 'Saison', abv: 6.5, sweet: 1, fruity: 1)
# Beer.create(name: 'Summer Ale', brewery_id: 15, style: 'Ale', abv: 5, crisp: 1, sweet: 1, citrus: 1, floral: 1, fruity: 1)
# Beer.create(name: 'Coors Light', brewery_id: 16, style: 'Lager', abv: 4.2, clean: 1, crisp: 1)
# Beer.create(name: 'Corona', brewery_id: 17, style: 'Lager', abv: 4.6, clean: 1, crisp: 1)
# Beer.create(name: 'Corona Light', brewery_id: 17, style: 'Lager', abv: 4.1, clean: 1, crisp: 1)
# Beer.create(name: 'Raspberry Ale', brewery_id: 18, style: 'Ale', abv: 5, sweet: 1, tart: 1, fruity: 1)
# Beer.create(name: '60 Min IPA', brewery_id: 19, style: 'IPA', abv: 6, hoppy: 1)
# Beer.create(name: 'Dos Equis Special', brewery_id: 20, style: 'Lager', abv: 4.5, clean: 1, crisp: 1)
# Beer.create(name: 'Flander Red', brewery_id: 21, style: 'Red Ale', abv: 6, sour: 1, sweet: 1, fruity: 1)
# Beer.create(name: 'Union Jack', brewery_id: 22, style: 'IPA', abv: 7.5, hoppy: 1)
# Beer.create(name: 'Draak', brewery_id: 23, style: 'Dark Triple', abv: 10.5, sweet: 1, caramel: 1)
# Beer.create(name: 'Daisy Cutter', brewery_id: 24, style: 'Pale Ale', abv: 5.2, hoppy: 1)
# Beer.create(name: 'Heineken', brewery_id: 11, style: 'Lager', abv: 5, clean: 1, crisp: 1)
# Beer.create(name: 'White Ale', brewery_id: 26, style: 'Ale', abv: 5, creamy: 1, smooth: 1, floral: 1)
# Beer.create(name: 'Nitro Milk Stout', brewery_id: 27, style: 'Stout', abv: 6, creamy: 1, rich: 1, smooth: 1, sweet: 1, chocolate: 1)
# Beer.create(name: 'Krankshaft', brewery_id: 28, style: 'Kolsch', abv: 5, crisp: 1, sweet: 1)
# Beer.create(name: 'Miller Lite', brewery_id: 29, style: 'Lager', abv: 4.2, clean: 1, crisp: 1)
# Beer.create(name: 'Old Rasputin Nitro', brewery_id: 30, style: 'Imperial Stout', abv: 9, rich: 1)
# Beer.create(name: 'Hennepin', brewery_id: 31, style: 'Saison', abv: 7.2, sweet: 1)
# Beer.create(name: 'Anti-Hero', brewery_id: 7, style: 'IPA', abv: 6.5, crisp: 1, bitter: 1, citrus: 1, floral: 1)
# Beer.create(name: 'Resin', brewery_id: 33, style: 'Imperial IPA', abv: 9.1, bitter: 1)
# Beer.create(name: 'Abbey Tripel', brewery_id: 35, style: 'Tripel', abv: 8.5, rich: 1, sweet: 1, fruity: 1)
# Beer.create(name: 'Stella Artois', brewery_id: 36, style: 'Lager', abv: 5.2, malty: 1, bitter: 1, sweet: 1, citrus: 1, fruity: 1)
# Beer.create(name: 'Oaked Arrogant Bastard', brewery_id: 37, style: 'Ale', abv: 7.2, sweet: 1, caramel: 1, fruity: 1, grapefruit: 1)
# Beer.create(name: 'Arctic Panzer Wolf', brewery_id: 38, style: 'Imperial IPA', abv: 9)
# Beer.create(name: 'Dreadnaught', brewery_id: 38, style: 'Imperial IPA', abv: 9.5, sweet: 1, caramel: 1, citrus: 1, fruity: 1)
# Beer.create(name: 'Strawberry Lambic', brewery_id: 39, style: 'Lambic', abv: 4, sweet: 1, fruity: 1)
# Beer.create(name: 'Tripel Karmeliet', brewery_id: 40, style: 'Tripel', abv: 8, smooth: 1, sweet: 1, fruity: 1)
# Beer.create(name: 'Prairie Path', brewery_id: 9, style: 'Golden Ale', abv: 5.1)
# Beer.create(name: 'Revenge Bourbon', brewery_id: 42, style: 'Brown Ale', abv: 5.7, creamy: 1, smooth: 1, sweet: 1, caramel: 1, vanilla: 1)
# Beer.create(name: 'Fin Du Monde', brewery_id: 43, style: 'Abbey Tripel', abv: 9)
# Beer.create(name: 'Red Streak', brewery_id: 44, style: 'Cider', abv: 5.2, crisp: 1, sweet: 1, fruity: 1)
# Beer.create(name: 'Banana Bread', brewery_id: 45, style: 'Ale', abv: 5.2, sweet: 1, banana: 1, fruity: 1)
# Beer.create(name: 'Bud Light', brewery_id: 36, style: 'Lager', abv: 4.2, clean: 1, crisp: 1)
# Beer.create(name: 'Budweiser', brewery_id: 36, style: 'Lager', abv: 5, clean: 1, crisp: 1)
# Beer.create(name: 'Heineken Light', brewery_id: 11, style: 'Lager', abv: 3.2, clean: 1, crisp: 1)
# Beer.create(name: 'Negro Modelo', brewery_id: 17, style: 'Dunkel Lager', abv: 5.3, bitter: 1, sweet: 1, fruity: 1)
# Beer.create(name: 'Sol', brewery_id: 20, style: 'Lager', abv: 4.5, malty: 1, spicy: 1, citrus: 1, floral: 1, fruity: 1, lemon: 1)
# Beer.create(name: 'Tecate', brewery_id: 20, style: 'Lager', abv: 4.5, clean: 1, crisp: 1)
# Beer.create(name: 'Victoria', brewery_id: 17, style: 'Lager', abv: 4, rich: 1, bitter: 1)
# Beer.create(name: 'O\'Doul\'s', brewery_id: 36, style: 'Non-alcoholic', abv: 0)
# 
# Bar.create(name: 'Haymarket Brewery', address: '737 W Randolph', city: 'Chicago', state: 'IL', zip: 60661, phone: '3126380700', website: 'http://haymarketbrewing.com/')
# Bar.create(name: 'Revolution Brewing', address: '2323 N Milwaukee Ave', city: 'Chicago', state: 'IL', zip: 60647, phone: '7732272739', website: 'http://revbrew.com/')
# Bar.create(name: 'Goose Island Brewery', address: '3535 N Clark St', city: 'Chicago', state: 'IL', zip: 60657, phone: '7738329040', website: 'http://www.gooseisland.com/')
# Bar.create(name: 'Stout', address: '642 N Clark St', city: 'Chicago', state: 'IL', zip: 60654, phone: 3124751390, website: 'http://stoutchicago.com/')
# Bar.create(name: 'Moe\'s Cantina', address: '155 W Kinzie', city: 'Chicago', state: 'IL', zip: 60654, phone: 3122452000, website: 'http://www.moescantina.com/')
# 
# BeerExperience.create(beer_id: 1, bar_id: 1, home: 1, local: 1, draft: 1, rarity: 5)
# BeerExperience.create(beer_id: 2, bar_id: 1, home: 1, local: 1, draft: 1, rarity: 5)
# BeerExperience.create(beer_id: 3, bar_id: 1, home: 1, local: 1, draft: 1, rarity: 5)
# BeerExperience.create(beer_id: 4, bar_id: 1, home: 1, local: 1, draft: 1, rarity: 5)
# BeerExperience.create(beer_id: 5, bar_id: 1, home: 1, local: 1, draft: 1, rarity: 5)
# BeerExperience.create(beer_id: 6, bar_id: 1, home: 1, local: 1, draft: 1, rarity: 5)
# BeerExperience.create(beer_id: 7, bar_id: 1, home: 1, local: 1, draft: 1, rarity: 5)
# BeerExperience.create(beer_id: 8, bar_id: 1, home: 1, local: 1, draft: 1, rarity: 5)
# BeerExperience.create(beer_id: 9, bar_id: 1, draft: 1, rarity: 4)
# BeerExperience.create(beer_id: 10, bar_id: 1, draft: 1, rarity: 4)
# BeerExperience.create(beer_id: 11, bar_id: 1, draft: 1, rarity: 4)
# BeerExperience.create(beer_id: 12, bar_id: 1, draft: 1, rarity: 4)
# BeerExperience.create(beer_id: 13, bar_id: 1, draft: 1, rarity: 3)
# BeerExperience.create(beer_id: 14, bar_id: 1, draft: 1, rarity: 4)
# BeerExperience.create(beer_id: 15, bar_id: 1, draft: 1, rarity: 3)
# BeerExperience.create(beer_id: 16, bar_id: 1, draft: 1, rarity: 5)
# BeerExperience.create(beer_id: 17, bar_id: 1, draft: 1, rarity: 4)
# BeerExperience.create(beer_id: 18, bar_id: 2, rarity: 5)
# BeerExperience.create(beer_id: 19, bar_id: 2, rarity: 5)
# BeerExperience.create(beer_id: 20, bar_id: 2, rarity: 5)
# BeerExperience.create(beer_id: 21, bar_id: 2, rarity: 5)
# BeerExperience.create(beer_id: 22, bar_id: 2, rarity: 4)
# BeerExperience.create(beer_id: 23, bar_id: 2, rarity: 5)
# BeerExperience.create(beer_id: 24, bar_id: 2, rarity: 4)
# BeerExperience.create(beer_id: 25, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 5)
# BeerExperience.create(beer_id: 26, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 5)
# BeerExperience.create(beer_id: 27, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 5)
# BeerExperience.create(beer_id: 28, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 5)
# BeerExperience.create(beer_id: 29, bar_id: 3, home: 1, local: 1, rarity: 2)
# BeerExperience.create(beer_id: 30, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 2)
# BeerExperience.create(beer_id: 31, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 4)
# BeerExperience.create(beer_id: 32, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 1)
# BeerExperience.create(beer_id: 33, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 5)
# BeerExperience.create(beer_id: 34, bar_id: 3, home: 1, local: 1, rarity: 5)
# BeerExperience.create(beer_id: 35, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 5)
# BeerExperience.create(beer_id: 36, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 5)
# BeerExperience.create(beer_id: 37, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 3)
# BeerExperience.create(beer_id: 38, bar_id: 3, home: 1, local: 1, rarity: 3)
# BeerExperience.create(beer_id: 39, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 3)
# BeerExperience.create(beer_id: 40, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 3)
# BeerExperience.create(beer_id: 41, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 4)
# BeerExperience.create(beer_id: 42, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 4)
# BeerExperience.create(beer_id: 43, bar_id: 3, home: 1, local: 1, rarity: 4)
# BeerExperience.create(beer_id: 44, bar_id: 3, home: 1, local: 1, rarity: 4)
# BeerExperience.create(beer_id: 45, bar_id: 3, home: 1, local: 1, draft: 1, rarity: 5)
# BeerExperience.create(beer_id: 46, bar_id: 3, local: 1, draft: 1, rarity: 3)
# BeerExperience.create(beer_id: 47, bar_id: 4, draft: 1, rarity: 4)
# BeerExperience.create(beer_id: 48, bar_id: 4, draft: 1, rarity: 3)
# BeerExperience.create(beer_id: 49, bar_id: 4, rarity: 1)
# BeerExperience.create(beer_id: 50, bar_id: 4, draft: 1, rarity: 3)
# BeerExperience.create(beer_id: 51, bar_id: 4, rarity: 1)
# BeerExperience.create(beer_id: 52, bar_id: 4, rarity: 5)
# BeerExperience.create(beer_id: 53, bar_id: 4, rarity: 4)
# BeerExperience.create(beer_id: 54, bar_id: 4, rarity: 1)
# BeerExperience.create(beer_id: 55, bar_id: 4, rarity: 1)
# BeerExperience.create(beer_id: 56, bar_id: 4, rarity: 1)
# BeerExperience.create(beer_id: 57, bar_id: 4, rarity: 4)
# BeerExperience.create(beer_id: 58, bar_id: 4, rarity: 3)
# BeerExperience.create(beer_id: 59, bar_id: 4, rarity: 1)
# BeerExperience.create(beer_id: 60, bar_id: 4, rarity: 5)
# BeerExperience.create(beer_id: 61, bar_id: 4, draft: 1, rarity: 4)
# BeerExperience.create(beer_id: 62, bar_id: 4, rarity: 5)
# BeerExperience.create(beer_id: 63, bar_id: 4, local: 1, draft: 1, rarity: 3)
# BeerExperience.create(beer_id: 64, bar_id: 4, rarity: 1)
# BeerExperience.create(beer_id: 48, bar_id: 4, rarity: 5)
# BeerExperience.create(beer_id: 66, bar_id: 4, draft: 1, rarity: 4)
# BeerExperience.create(beer_id: 67, bar_id: 4, local: 1, draft: 1, rarity: 4)
# BeerExperience.create(beer_id: 68, bar_id: 4, rarity: 1)
# BeerExperience.create(beer_id: 69, bar_id: 4, draft: 1, rarity: 4)
# BeerExperience.create(beer_id: 70, bar_id: 4, draft: 1, rarity: 3)
# BeerExperience.create(beer_id: 71, bar_id: 4, local: 1, draft: 1, rarity: 4)
# BeerExperience.create(beer_id: 72, bar_id: 4, draft: 1, rarity: 4)
# BeerExperience.create(beer_id: 73, bar_id: 4, rarity: 4)
# BeerExperience.create(beer_id: 74, bar_id: 4, rarity: 2)
# BeerExperience.create(beer_id: 75, bar_id: 4, rarity: 3)
# BeerExperience.create(beer_id: 76, bar_id: 4, draft: 1, rarity: 4)
# BeerExperience.create(beer_id: 77, bar_id: 4, rarity: 4)
# BeerExperience.create(beer_id: 78, bar_id: 4, rarity: 4)
# BeerExperience.create(beer_id: 79, bar_id: 4, rarity: 5)
# BeerExperience.create(beer_id: 80, bar_id: 4, rarity: 3)
# BeerExperience.create(beer_id: 81, bar_id: 4, rarity: 4)
# BeerExperience.create(beer_id: 82, bar_id: 4, rarity: 4)
# BeerExperience.create(beer_id: 83, bar_id: 4, local: 1, draft: 1, rarity: 3)
# BeerExperience.create(beer_id: 84, bar_id: 4, rarity: 3)
# BeerExperience.create(beer_id: 42, bar_id: 4, local: 1, draft: 1, rarity: 4)
# BeerExperience.create(beer_id: 39, bar_id: 4, local: 1, draft: 1, rarity: 3)
# BeerExperience.create(beer_id: 37, bar_id: 4, local: 1, rarity: 3)
# BeerExperience.create(beer_id: 13, bar_id: 4, draft: 1, rarity: 4)
# BeerExperience.create(beer_id: 10, bar_id: 4, rarity: 3)
# BeerExperience.create(beer_id: 85, bar_id: 5, rarity: 1)
# BeerExperience.create(beer_id: 86, bar_id: 5, rarity: 1)
# BeerExperience.create(beer_id: 87, bar_id: 5, rarity: 1)
# BeerExperience.create(beer_id: 88, bar_id: 5, rarity: 2)
# BeerExperience.create(beer_id: 89, bar_id: 5, rarity: 2)
# BeerExperience.create(beer_id: 90, bar_id: 5, rarity: 2)
# BeerExperience.create(beer_id: 91, bar_id: 5, rarity: 2)
# BeerExperience.create(beer_id: 92, bar_id: 5, rarity: 2)
# BeerExperience.create(beer_id: 54, bar_id: 5, rarity: 1)
# BeerExperience.create(beer_id: 51, bar_id: 5, rarity: 1)
# BeerExperience.create(beer_id: 30, bar_id: 5, rarity: 2)
# BeerExperience.create(beer_id: 49, bar_id: 5, rarity: 1)
# BeerExperience.create(beer_id: 59, bar_id: 5, rarity: 1)
# BeerExperience.create(beer_id: 64, bar_id: 5, rarity: 1)
# BeerExperience.create(beer_id: 74, bar_id: 5, rarity: 2)
# 
# Team.create(name: 'Emily Ellison', description: 'Data Nerd.', image: 'emily_in_color.jpg')
# Team.create(name: 'Stella Fayman', description: 'Entrepreneurial Rockstar.', image: 'stella_in_color.jpg')
# Team.create(name: 'Zak Boswell', description: 'UX Ninja.', image: 'zak_in_color.jpg')
# Team.create(name: 'Fernando Diaz', description: 'Code Detective.', image: 'fernando_in_color.jpg')
# Team.create(name: 'Mike Ebert', description: 'Agile Scrum Master.', image: 'mike_in_color.png')
# Team.create(name: 'Chad Hendry', description: 'Programming Guru.', image: 'chad.jpg')
# 

Brewery.create(name: 'BBNP Brewery', country: 'Czech Republic')
Brewery.create(name: 'Lost Coast', city: 'Eureka', state: 'CA', country: 'USA')
Brewery.create(name: 'Boddington\'s', country: 'England')
Brewery.create(name: 'Krombacher Privatbrauerei Kreuztal', country: 'Germany')
Brewery.create(name: 'Greene King', country: 'England')
Brewery.create(name: 'Wells & Young\'s', country: 'England')
Brewery.create(name: 'Miller', city: 'Milwaukee', state: 'WI', country: 'USA')
Brewery.create(name: 'Sam Adams', city: 'Boston', state: 'MA', country: 'USA')
Brewery.create(name: 'Lagunitas', city: 'Lagunitas', state: 'CA', country: 'USA')

Beer.create(name: 'Domaine DuPage', brewery_id: 9, style: 'French Country Ale', abv: 5.9, smooth: 1, sweet: 1, caramel: 1)
Beer.create(name: 'Czechvar', brewery_id: 46, style: 'Pilsner', abv: 5)
Beer.create(name: 'India Pale Ale')
Beer.create(name: 'Redbridge', brewery_id: 36, style: 'Gluten-Free', abv: 4.8)
Beer.create(name: 'Kirin Ichiban', brewery_id: 36, style: 'Pilsner', abv: 5)
Beer.create(name: 'Bombardier', brewery_id: 51, style: 'Ale', abv: 4.7)
Beer.create(name: 'Leffe Blond', brewery_id: 36, style: 'Abbey', abv: 6.6)
Beer.create(name: 'Wexford Irish Cream', brewery_id: 50, style: 'ESB', abv: 5)
Beer.create(name: 'Krombacher Pils', brewery_id: 49, style: 'Pilsner', abv: 4.8)
Beer.create(name: 'Hoegaarden', brewery_id: 36, style: 'Witbier', abv: 5)
Beer.create(name: 'Downtown Brown', brewery_id: 47, style: 'Nut Brown Ale', abv: 5)
Beer.create(name: 'Boddington\'s', brewery_id: 48, style: 'Ale', abv: 4.7)
Beer.create(name: 'Miller Genuine Draft', brewery_id: 52, style: 'Pilsner', abv: 4.7)
Beer.create(name: 'Sam Adams', brewery_id: 53, style: 'Lager', abv: 4.9)
Beer.create(name: 'Lagunitas', brewery_id: 54, style: 'Unknown')

Bar.create(name: 'Leona\'s', address: '1936 W Augusta Blvd', city: 'Chicago', state: 'IL', zip: 60622, phone: '7732924300', website: 'http://leonas.com/')

BeerExperience.create(beer_id: 93, bar_id: 6, local: 1, rarity: 3)
BeerExperience.create(beer_id: 94, bar_id: 6, rarity: 4)
BeerExperience.create(beer_id: 34, bar_id: 6, rarity: 1)
BeerExperience.create(beer_id: 96, bar_id: 6, rarity: 4)
BeerExperience.create(beer_id: 97, bar_id: 6, rarity: 3)
BeerExperience.create(beer_id: 98, bar_id: 6, rarity: 4)
BeerExperience.create(beer_id: 99, bar_id: 6, rarity: 2)
BeerExperience.create(beer_id: 100, bar_id: 6, rarity: 4)
BeerExperience.create(beer_id: 101, bar_id: 6, rarity: 3)
BeerExperience.create(beer_id: 102, bar_id: 6, rarity: 2)
BeerExperience.create(beer_id: 103, bar_id: 6, rarity: 3)
BeerExperience.create(beer_id: 104, bar_id: 6, rarity: 2)
BeerExperience.create(beer_id: 105, bar_id: 6, rarity: 1)
BeerExperience.create(beer_id: 106, bar_id: 6, rarity: 1)
BeerExperience.create(beer_id: 46, bar_id: 6, local: 1, rarity: 3)
BeerExperience.create(beer_id: 68, bar_id: 6, rarity: 1)
BeerExperience.create(beer_id: 86, bar_id: 6, rarity: 1)
BeerExperience.create(beer_id: 55, bar_id: 6, rarity: 1)
BeerExperience.create(beer_id: 64, bar_id: 6, rarity: 1)
BeerExperience.create(beer_id: 49, bar_id: 6, rarity: 1)
BeerExperience.create(beer_id: 74, bar_id: 6, rarity: 2)
BeerExperience.create(beer_id: 107, bar_id: 6, rarity: 3)